version: '3'
services:
  app:
    build: .
    tty: true
    ports:
      - 8000:8000
    volumes:
      - .:/submarine-online-ak
      - node_modules:/submarine-online-ak/node_modules
volumes:
  node_modules:
